- alias: Turn on/off cat fountain
  initial_state: True
  trigger:
    - platform: time
      # matches every hour whole
      minutes: 0
      seconds: 00
#  condition:
#    - condition: time
#      after: '06:00:00'
#      before: '24:00:00'
  condition:
    condition: state
    entity_id: input_boolean.catfountain_automatic
    state: 'on'
  action:
    - service: switch.toggle
      entity_id: switch.kitchen_01

#- alias: Check cat fountain and send mail
#  trigger:
#    platform: state
#    entity_id: switch.kitchen_01
#  action:
#    service: notify.mailnotifier
#    data:
#      title: "Notification: Status Katzenbrunnen"
#      message: "Test"

- alias: Check cat fountain and show notification
  initial_state: True
  trigger:
    - platform: state
      entity_id: switch.kitchen_01
  condition:
    condition: state
    entity_id: input_boolean.catfountain_notify
    state: 'on'
  action:
    - service: persistent_notification.create
      data_template:
        title: "Notification: Status Katzenbrunnen"
        message: >
          Katzenbrunnen ist jetzt {% if is_state('switch.kitchen_01', 'on') %}an{% else %}aus{% endif %} ({{now().strftime("%H:%M:%S")}})
        notification_id: 'catfountain'

- alias: Check network alarm
  initial_state: True
  trigger:
    #check every 5 minutes
    - platform: time
      minutes: '/5'
      seconds: 00
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.netmonitor_downrate_current_alarm_max_notify
        state: 'on'
      - condition: template
        value_template: '{{ (states.sensor.netmonitor_downrate_current_sensor_template.state | float) > (states.input_number.netmonitor_downrate_current_alarm_max.state | float) }}'
  action:
    - service: persistent_notification.create
      data_template:
        title: "Notification: Status Netzwerk"
        message: 'Aktueller DownStream: {{ (states.sensor.netmonitor_downrate_current_sensor_template.state | float | round(1)) }} Mbit/s ({{now().strftime("%H:%M:%S")}})'
        notification_id: 'networkalarm'
