homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation_home
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  # Customization file
  customize: !include customization/customize.yaml

frontend: !include customization/frontend.yaml

panel_custom: !include customization/panel_custom.yaml

# Enables configuration UI
config:

http:
  api_password: !secret http_api_password

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  reporting: False
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
#logbook:

# Enables a map showing the location of tracked devices
#map:

# Track the sun
sun:

#logging
logger:
#  default: critical
#  logs:
#    homeassistant.components.automation: debug

sensor: !include_dir_merge_list sensors/normal/
binary_sensor: !include sensors/binary/binary_sensors.yaml
switch: !include_dir_merge_list switches/
group: !include_dir_merge_named groups/
automation: !include_dir_list automations/
script: !include scripts/scripts.yaml
notify: !include_dir_merge_list notifier/
device_tracker: !include_dir_merge_list device_trackers/
#input_boolean: !include inputs/input_booleans.yaml
input_number: !include inputs/input_numbers.yaml
input_select: !include inputs/input_selects.yaml
input_text: !include inputs/input_texts.yaml
media_player: !include_dir_merge_list media_players/
camera: !include_dir_merge_list cameras/
weblink: !include weblinks.yaml
history_graph: !include graphs/temperature.yaml
#history_graph: !include_dir_merge_list graphs/
weather: !include_dir_merge_list weather/
shell_command: !include scripts/shell/shellcommands.yaml
