### device_trackers ###

- platform: fritz
  new_device_defaults:
    track_new_devices: False
    hide_if_away: False

- platform: ping
  hosts:
    webhost: 192.168.178.21
    zerosensor01: 192.168.178.209
