### sensors ###

- platform: yr
  name: weather_yr
  monitored_conditions:
    - temperature
    - symbol
    - precipitation
    - windSpeed
    - pressure
    - windDirection
    - humidity
    - fog
    - cloudiness

- platform: yr
  name: weather_yr_future4h
  forecast: 4
  monitored_conditions:
    - symbol
    - temperature

- platform: yr
  name: weather_yr_future24h
  forecast: 24
  monitored_conditions:
    - symbol
    - temperature

- platform: fritzbox_netmonitor
  name: netmonitor

- platform: fritzbox_callmonitor
  name: callmonitor
  prefixes:
    - '+49'
    - '+4989'
    - '089'

- platform: synologydsm
  name: nasmonitor
  host: 192.168.178.57
  username: !secret synology_user
  password: !secret synology_password
  monitored_conditions:
    - cpu_total_load
    - memory_real_usage
    - network_up
    - network_down
    - disk_name
    - disk_status
    - disk_temp

- platform: systemmonitor
  name: hassmonitor
  resources:
    - type: memory_use_percent
    - type: processor_use
    - type: network_in
    - type: network_out
    - type: last_boot
    - type: since_last_boot

- platform: pi_hole
  name: piholemonitor
  host: 192.168.178.21
  monitored_conditions:
    - ads_blocked_today
    - ads_percentage_today
    - unique_clients
    - domains_being_blocked

- platform: version
  name: version_current

  # templates
- platform: template
  sensors:
    googledns_template:
      value_template: '{% if is_state("binary_sensor.googledns", "on") %} {{ states.binary_sensor.googledns.attributes.round_trip_time_avg }} {% else %}Offline{% endif %}'
      
    webhost_sensor_template:
      value_template: "{% if is_state('device_tracker.webhost', 'home') %}online{% else %}offline{% endif %}"

    zerosensor01_sensor_template:
      value_template: "{% if is_state('device_tracker.zerosensor01', 'home') %}online{% else %}offline{% endif %}"

    office_temperature_template: #sensor.office_temperature is a HTTP sensor - only initialized by api call
      value_template: "{% if states.sensor.office_temperature is defined %} {{ states.sensor.office_temperature.state | round(1) }} {% else %}Unbekannt{% endif %}"

    office_humidity_template: #sensor.office_humidity is a HTTP sensor - only initialized by api call
        value_template: "{% if states.sensor.office_humidity is defined %} {{ states.sensor.office_humidity.state | round(1) }} {% else %}Unbekannt{% endif %}"

    netmonitor_downrate_sensor_template:
      unit_of_measurement: 'Mbit/s'
      value_template: "{{ (states.sensor.netmonitor.attributes.max_byte_rate_down * 8 / 1000 / 1000 | float) | round(1) }}"

    netmonitor_uprate_sensor_template:
      unit_of_measurement: 'Mbit/s'
      value_template: "{{ (states.sensor.netmonitor.attributes.max_byte_rate_up * 8 / 1000 / 1000 | float) | round(1) }}"

    netmonitor_downrate_current_sensor_template:
      unit_of_measurement: 'Mbit/s'
      value_template: "{{ (states.sensor.netmonitor.attributes.transmission_rate_down * 8 / 1000 / 1000 | float) | round(1) }}"
