name: Home
views:
  - title: Home
    id: home
    icon: mdi:home-assistant
    cards:
      - type: entities
        title: Anwesenheit
        entities:
          - device_tracker.his_s8
          - device_tracker.her_iphone

      - type: entities
        title: Büro
        entities:
          - sensor.office_temperature_template
          - sensor.office_humidity_template
          - sensor.hispc_sensor_template
          - switch.wol_hispc

      - type: entities
        title: Küche
        entities:
          - switch.kitchen_01

      - type: media-control
        title: Samsung Smart TV
        entity: media_player.samsungsmarttv

  - title: Wetter
    id: weather
    icon: mdi:weather-partlycloudy
    cards:
      - type: 'custom:custom-weather-animated'
        entity: input_boolean.weather_customcardhack

      - type: history-graph
        title: Temperaturen (24h)
        entities:
          - sensor.weather_yr_temperature
          - sensor.office_temperature_template

      - type: glance
        title: Wetter YR
        entities:
          - sensor.weather_yr_symbol
          - sun.sun
          - sensor.weather_yr_temperature
          - sensor.weather_yr_cloudiness
          - sensor.weather_yr_humidity
          - sensor.weather_yr_wind_direction
          - sensor.weather_yr_wind_speed
          - sensor.weather_yr_fog
          - sensor.weather_yr_precipitation
          - sensor.weather_yr_pressure

      - type: horizontal-stack
        cards:
          - type: picture-entity
            title: Regenkarte Deutschland
            image:
            camera_image: camera.weather_stillimage_00
            entity: camera.weather_stillimage_00

          - type: picture-entity
            title: Satellit Europa
            image:
            camera_image: camera.weather_stillimage_01
            entity: camera.weather_stillimage_01

  - title: Netzwerk
    id: network
    icon: mdi:network
    cards:
      - type: entities
        title: Links
        entities:
          - weblink.router
          - weblink.nas
          - weblink.pihole

      - type: entities
        title: Pings
        entities:
          - sensor.googledns_template

      - type: entities
        title: FritzBox
        entities:
          - sensor.netmonitor
          - sensor.callmonitor
          - sensor.netmonitor_downrate_sensor_template
          - sensor.netmonitor_uprate_sensor_template
          - sensor.netmonitor_downrate_current_sensor_template

      - type: entities
        title: Webhost / PiHole
        entities:
          #- device_tracker.webhost
          - sensor.webhost_sensor_template
          - sensor.piholemonitor_ads_blocked_today
          - sensor.piholemonitor_ads_percentage_blocked_today
          - sensor.piholemonitor_dns_unique_clients
          - sensor.piholemonitor_domains_blocked

      - type: entities
        title: Home Assistant
        entities:
          - sensor.memory_use_percent
          - sensor.processor_use
          - sensor.network_in
          - sensor.network_out
          - sensor.last_boot
          - sensor.since_last_boot

      - type: entities
        title: Pi Zero Sensor 01
        entities:
          - sensor.zerosensor01_sensor_template

      - type: entities
        title: Synology NAS
        entities:
          - sensor.cpu_load_total
          - sensor.memory_usage_real
          - sensor.network_up
          - sensor.network_down
          - sensor.name_sda
          - sensor.status_sda
          - sensor.temperature_sda
          - sensor.name_sdb
          - sensor.status_sdb
          - sensor.temperature_sdb

  - title: Pendelei
    id: commute
    icon: mdi:car
    cards:
      #- type: 'custom:state-card-gasstation'
      #  entity: script.gasstation

      - type: entities
        title: Pendelei Puh
        entities:
          - sensor.commute_time_her_template
          - sensor.commute_distance_her_template
          - sensor.commute_timestamp_her_template

      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: picture-entity
                title: !secret commute_highway_03
                image:
                camera_image: camera.commute_highway_03
                entity: camera.commute_highway_03

              - type: picture-entity
                title: !secret commute_highway_04
                image:
                camera_image: camera.commute_highway_04
                entity: camera.commute_highway_04

          - type: horizontal-stack
            cards:
              - type: picture-entity
                title: !secret commute_highway_01
                image:
                camera_image: camera.commute_highway_01
                entity: camera.commute_highway_01

              - type: picture-entity
                title: !secret commute_highway_02
                image:
                camera_image: camera.commute_highway_02
                entity: camera.commute_highway_02

  - title: Settings
    id: settings
    icon: mdi:tune
    cards:
      - type: entities
        title: Info
        entities:
          - sensor.version_current
          - sensor.version_available

      - type: entities
        title: Theme
        entities:
          - input_select.hass_template
          - automation.theme__aendern
          - automation.theme__nachttag
          - automation.theme__tagnacht

      - type: entities
        title: Netzwerk Alarm
        entities:
          - input_number.netmonitor_downrate_current_alarm_max
          - automation.netzwerk__alarm

      - type: entities
        title: Telefon
        entities:
          - variable.last_caller
          - sensor.incomingcaller_template
          - automation.telefon__verpasster_anruf
          - automation.telefon__einkommender_anruf_protokoll

      - type: entities
        title: Katzen
        entities:
          - automation.katzenbrunnen__anzeige
          - automation.katzenbrunnen__stundlich_automatisch_anaus
          - automation.katzenbrunnen__tts
