- platform: fritzbox_netmonitor
  name: netmonitor

- platform: fritzbox_callmonitor
  name: callmonitor
  username: !secret fritzbox_user
  password: !secret fritzbox_password
  phonebook: 0
  prefixes:
    - '+49'
    - '+4989'
    - '089'
