- platform: systemmonitor
  name: hassmonitor
  resources:
    - type: memory_use_percent
    - type: processor_use
    - type: network_in
    - type: network_out
    - type: last_boot
    - type: since_last_boot

- platform: version
  name: version_current
