- platform: systemmonitor
  name: hassmonitor
  resources:
    - type: memory_use_percent
    - type: processor_use
    - type: network_in
    - type: network_out
    - type: last_boot
    - type: since_last_boot

- platform: version
  name: version_current

- platform: command_line
  name: version_available
  command: python3 -c "import requests; print(requests.get('https://pypi.python.org/pypi/homeassistant/json').json()['info']['version'])"
