- platform: template
  sensors:
    incomingcaller_template:
      value_template: "{{ states.sensor.callmonitor.attributes.from_name }}"

    googledns_template:
      value_template: '{% if is_state("binary_sensor.googledns", "on") %} {{ states.binary_sensor.googledns.attributes.round_trip_time_avg }} {% else %}Offline{% endif %}'

    webhost_sensor_template:
      value_template: "{% if is_state('device_tracker.webhost', 'home') %}online{% else %}offline{% endif %}"

    hispc_sensor_template:
      value_template: "{% if is_state('device_tracker.hispc', 'home') %}online{% else %}offline{% endif %}"

    zerosensor01_sensor_template:
      value_template: "{% if is_state('device_tracker.zerosensor01', 'home') %}online{% else %}offline{% endif %}"

    office_temperature_template: #sensor.office_temperature is a HTTP sensor - only initialized by api call
      value_template: "{% if states.sensor.office_temperature is defined %} {{ states.sensor.office_temperature.state | round(1) }} {% else %}Unbekannt{% endif %}"

    office_humidity_template: #sensor.office_humidity is a HTTP sensor - only initialized by api call
        value_template: "{% if states.sensor.office_humidity is defined %} {{ states.sensor.office_humidity.state | round(1) }} {% else %}Unbekannt{% endif %}"

    netmonitor_downrate_sensor_template:
      unit_of_measurement: 'Mbit/s'
      value_template: "{{ (states.sensor.netmonitor.attributes.max_byte_rate_down * 8 / 1000 / 1000 | float) | round(1) }}"

    netmonitor_uprate_sensor_template:
      unit_of_measurement: 'Mbit/s'
      value_template: "{{ (states.sensor.netmonitor.attributes.max_byte_rate_up * 8 / 1000 / 1000 | float) | round(1) }}"

    netmonitor_downrate_current_sensor_template:
      unit_of_measurement: 'Mbit/s'
      value_template: "{{ (states.sensor.netmonitor.attributes.transmission_rate_down * 8 / 1000 / 1000 | float) | round(1) }}"

    gasprices_price_01_template:
      value_template: '{{ states.sensor.gasprices.attributes.stations[0]["e5"] }}'
      unit_of_measurement: '€'
      entity_id: sensor.gasprices

    gasprices_name_01_template:
      value_template: '{{ states.sensor.gasprices.attributes.stations[0]["name"].title() }}'
      entity_id: sensor.gasprices

    gasprices_price_02_template:
      value_template: '{{ states.sensor.gasprices.attributes.stations[1]["e5"] }}'
      unit_of_measurement: '€'
      entity_id: sensor.gasprices

    gasprices_name_02_template:
      value_template: '{{ states.sensor.gasprices.attributes.stations[1]["name"].title() }}'
      entity_id: sensor.gasprices
