alias: Netzwerk - Alarm
initial_state: True
trigger:
  #check every 5 minutes
  - platform: time
    minutes: '/5'
    seconds: 00
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_boolean.netmonitor_downrate_current_alarm_max_notify
      state: 'on'
    - condition: template
      value_template: '{{ (states.sensor.netmonitor_downrate_current_sensor_template.state | float) > (states.input_number.netmonitor_downrate_current_alarm_max.state | float) }}'
action:
  - service: persistent_notification.create
    data_template:
      title: "Notification: Status Netzwerk"
      message: 'Aktueller DownStream: {{ (states.sensor.netmonitor_downrate_current_sensor_template.state | float | round(1)) }} Mbit/s ({{now().strftime("%H:%M:%S")}})'
      notification_id: 'networkalarm'
  - service: notify.mailnotifier
    data:
      title: "Notification: Status Netzwerk"
      message: 'Aktueller DownStream: {{ (states.sensor.netmonitor_downrate_current_sensor_template.state | float | round(1)) }} Mbit/s ({{now().strftime("%H:%M:%S")}})'
