alias: Telefon - Einkommender Anruf Protokoll
id: telephone_incoming_call
trigger:
  - platform: state
    entity_id: sensor.callmonitor
    from: 'idle'
    to: 'ringing'
action:
  - service: variable.set_variable
    data:
      variable: last_caller
      value_template: '{{ states.sensor.callmonitor.attributes.from_name }}'
  - service: script.turn_on
    entity_id: script.speak_incoming_call
