alias: Telefon - Verpasster Anruf
id: telephone_missed_call
trigger:
  - platform: state
    entity_id: sensor.callmonitor
    from: 'ringing'
    to: 'idle'
action:
  - service: notify.mailnotifier
    data:
      title: "Verpasster Anruf"
      message: 'Von: {{ states.input_text.text_last_call.state }} um {{ now().strftime("%H:%M:%S") }}'
