alias: Theme - Tag-Nacht
id: day_to_night_theme
trigger:
  - platform: state
    entity_id: sun.sun
    from: 'above_horizon'
    to: 'below_horizon'
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.hass_template
      option: 'dark'
