- platform: generic
  name: commute_highway_01
  still_image_url: !secret commute_highway_01_url

- platform: generic
  name: commute_highway_02
  still_image_url: !secret commute_highway_02_url

- platform: generic
  name: commute_highway_03
  still_image_url: !secret commute_highway_03_url

- platform: generic
  name: commute_highway_04
  still_image_url: !secret commute_highway_04_url
